# .github/workflows/lint.yml
name: CI – Python Lint Check

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # ❶ リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # ❷ Python 3.12 をセットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ❸ プロジェクト依存関係をインストール
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # ❹ pre-commit フックを実行
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
